site_name: Franzininho WiFi - CircuitPython
site_favicon: img/favicon.ico

repo_url: https://github.com/Franzininho/exemplos-circuitpython/tree/main/documentacao

nav:
    - Primeiros passos: index.md
    - Hello, World! (Pisca LED): 01-hello.md
    - Controlando a intensidade do brilho de LED: 02-intensidade-led.md
    - Tecla liga e desliga: 03-tecla_liga_desliga.md
    - Sobre: about.md


theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - python

markdown_extensions:
  - admonition
