site_name: Franzininho WiFi - CircuitPython
site_favicon: img/favicon.ico

nav:
    - Primeiros passos: index.md
    - Hello, World! (Pisca LED): exemplos/01-hello.md
    - Controlando a intensidade do brilho de LED: exemplos/02-intensidade-led.md
    - Sobre: about.md


theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - python
